<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <RootNamespace>TreeSitter.CodeGraph</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet Package Metadata -->
    <PackageId>TreeSitter.CodeGraph</PackageId>
    <Title>TreeSitter.CodeGraph</Title>
    <Authors>Jianyao</Authors>
    <PackageDescription>Tree-Sitter based static code graph analyzer and multi-language codebase scanner for .NET.</PackageDescription>
    <Description>Tree-Sitter based static code graph analyzer and multi-language codebase scanner for .NET.</Description>
    <PackageTags>tree-sitter;code-analysis;code-graph;ast;static-analysis</PackageTags>
    <RepositoryUrl>https://github.com/Jianyao17/TreeSitter.CodeGraph</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TreeSitter.DotNet" Version="1.3.0" />
  </ItemGroup>

</Project>
